# Generated by Django 4.2.16 on 2026-05-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('nse_url', models.URLField(blank=True)),
                ('bse_url', models.URLField(blank=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('about_company', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=30, unique=True)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('color_hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(max_length=30, unique=True)),
                ('sector_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=40, unique=True)),
                ('fiscal_year', models.IntegerField()),
                ('quarter', models.CharField(blank=True, max_length=4)),
                ('is_ttm', models.BooleanField(default=False)),
                ('is_half_year', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProsConsFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.company')),
            ],
        ),
        migrations.CreateModel(
            name='MlScoreFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField()),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profitability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('growth_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('leverage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cashflow_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dividend_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trend_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('health_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.healthlabel')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='warehouse.sector'),
        ),
        migrations.CreateModel(
            name='ProfitLossFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('opm_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('dividend_payout_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_profit_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expense_ratio_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('interest_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.yeardimension')),
            ],
            options={
                'unique_together': {('symbol', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('investing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('financing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cash_conversion_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.yeardimension')),
            ],
            options={
                'unique_together': {('symbol', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reserves', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fixed_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cwip', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('equity_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.yeardimension')),
            ],
            options={
                'unique_together': {('symbol', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=10)),
                ('compounded_sales_growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('compounded_profit_growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock_price_cagr_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roe_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.company')),
            ],
            options={
                'unique_together': {('symbol', 'period_label')},
            },
        ),
    ]
